### ISSUE TITLE
[Channel] FPDA - Federação Portuguesa de Autismo

### ISSUE THREAD

**Issue by pmencarnacao** [a-STEP-action/a-STEP#11]
Information about the proposed communication channel:

Channel Name or label: FPDA - Federação Portuguesa de Autismo
Contact address: fpda@fpda.pt; Rua José Luís Garcia Rodrigues, Bairro do Alto da Ajuda, 1300 - 565 Lisboa, Portugal
Type: Federation of associations for people on the ASD
Disability focus: Autism
Country and language: Portugal / Portuguese 
Link: https://www.fpda.pt/
Proposed by: Pedro Encarnação
Status: Proposal

* Types include: Care givers, end- users, teachers, relatives, parents, friends researchers, colleagues, HR,  developers, experts

**Comment by gerazov** [comment]
The organization was added to the Wiki - thank you for your contribution Pedro :pray:
