### ISSUE TITLE
[Channel] HUMANITAS

### ISSUE THREAD

**Issue by pmencarnacao** [a-STEP-action/a-STEP#12]
Information about the proposed communication channel:

Channel Name or label: HUMANITAS Federação Portuguesa para a Deficiência Mental
Contact address: humanitas@humanitas.org.pt; Praça de Londres, 9 – 4º Esq., 1000-192 Lisboa, Portugal
Type: Federation of associations for persons with cognitive disabilities
Disability focus: Cognitive disabilities
Country and language: Portugal / Portuguese
Link: https://humanitas.org.pt/
Proposed by: Pedro Encarnação
Status: Proposal

* Types include: Care givers, end- users, teachers, relatives, parents, friends researchers, colleagues, HR,  developers, experts

**Comment by gerazov** [comment]
The organization was added to the Wiki - thank you for your contribution Pedro :pray:
